import hashlib
import secrets
from datetime import datetime, timedelta, timezone

import bcrypt
import jwt

from core.config import settings

_BCRYPT_MAX_BYTES = 72
_PASSWORD_RESET_TOKEN_BYTES = 32


def hash_password(plain_password: str) -> str:
    """Hash a plaintext password using bcrypt."""
    if not plain_password:
        raise ValueError("Password must not be empty.")

    password_bytes = plain_password.encode("utf-8")
    if len(password_bytes) > _BCRYPT_MAX_BYTES:
        raise ValueError(
            f"Password must not exceed {_BCRYPT_MAX_BYTES} bytes."
        )

    salt = bcrypt.gensalt()
    hashed_bytes = bcrypt.hashpw(password_bytes, salt)
    return hashed_bytes.decode("utf-8")


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plaintext password against a bcrypt hash."""
    if not plain_password or not hashed_password:
        return False

    try:
        return bcrypt.checkpw(
            plain_password.encode("utf-8"), hashed_password.encode("utf-8")
        )
    except ValueError:
        return False


def create_access_token(
    subject: str, expires_delta: timedelta | None = None
) -> str:
    """Generate a signed JWT access token for the given subject.

    `subject` should be a stable identifier (e.g. a user id) and is stored
    in the `sub` claim. Expiration defaults to
    `settings.jwt_access_token_expire_minutes` and is stored, timezone-aware
    in UTC, in the `exp` claim.
    """
    if not subject:
        raise ValueError("Token subject must not be empty.")

    issued_at = datetime.now(timezone.utc)
    expires_at = issued_at + (
        expires_delta
        if expires_delta is not None
        else timedelta(minutes=settings.jwt_access_token_expire_minutes)
    )

    payload = {
        "sub": subject,
        "iat": issued_at,
        "exp": expires_at,
    }
    return jwt.encode(payload, settings.jwt_secret_key, algorithm=settings.jwt_algorithm)


def generate_password_reset_token() -> str:
    """Generate a cryptographically secure, high-entropy password reset token."""
    return secrets.token_urlsafe(_PASSWORD_RESET_TOKEN_BYTES)


def hash_reset_token(raw_token: str) -> str:
    """Hash a password reset token for storage and lookup.

    Reset tokens are high-entropy random values generated by this service
    (unlike user-chosen passwords), so a fast deterministic SHA-256 hash is
    used instead of bcrypt to allow direct lookup by hash.
    """
    if not raw_token:
        raise ValueError("Token must not be empty.")

    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


def decode_access_token(token: str) -> dict:
    """Decode and validate a JWT access token, returning its payload.

    Raises `jwt.ExpiredSignatureError` if the token has expired, and
    `jwt.InvalidTokenError` (or a subclass) for any other validation
    failure, such as a bad signature or malformed token.
    """
    if not token:
        raise jwt.InvalidTokenError("Token must not be empty.")

    return jwt.decode(
        token, settings.jwt_secret_key, algorithms=[settings.jwt_algorithm]
    )
