"""create application_settings table

Revision ID: 13dee62a63b4
Revises: 8ff2a6e4d843
Create Date: 2026-07-23 20:04:02.784729

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dee62a63b4'
down_revision: Union[str, None] = '8ff2a6e4d843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEED_SETTINGS = (
    {
        "key": "measurement_overdue_days",
        "value": "14",
        "description": (
            "Number of days after which a client is considered overdue for "
            "measurements."
        ),
    },
    {
        "key": "subscription_expired_days",
        "value": "30",
        "description": (
            "Number of days after subscription end_date after which a "
            "client moves from EXPIRED to INACTIVE."
        ),
    },
)

application_settings_table = sa.table(
    "application_settings",
    sa.column("id", sa.UUID()),
    sa.column("key", sa.String()),
    sa.column("value", sa.Text()),
    sa.column("description", sa.Text()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        application_settings_table,
        [{"id": uuid.uuid4(), **seed} for seed in SEED_SETTINGS],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_settings')
    # ### end Alembic commands ###
