"""create client trainer assignments table

Revision ID: db12eca198a8
Revises: 9f276cc489a6
Create Date: 2026-07-22 21:09:46.313739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db12eca198a8'
down_revision: Union[str, None] = '9f276cc489a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_trainer_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'trainer_id', name='uq_client_trainer')
    )
    op.create_index('idx_assignment_client', 'client_trainer_assignments', ['client_id'], unique=False)
    op.create_index('idx_assignment_trainer', 'client_trainer_assignments', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assignment_trainer', table_name='client_trainer_assignments')
    op.drop_index('idx_assignment_client', table_name='client_trainer_assignments')
    op.drop_table('client_trainer_assignments')
    # ### end Alembic commands ###
