"""add sessions_per_week to subscription plans and subscriptions

Revision ID: dd617a9bfa18
Revises: 13dee62a63b4
Create Date: 2026-07-23 20:24:29.060457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd617a9bfa18'
down_revision: Union[str, None] = '13dee62a63b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('sessions_per_week', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('plan_sessions_per_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'plan_sessions_per_week')
    op.drop_column('subscription_plans', 'sessions_per_week')
    # ### end Alembic commands ###
