"""create sessions table

Revision ID: f638630c2dbe
Revises: b5d7756411e1
Create Date: 2026-07-23 06:46:35.130566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f638630c2dbe'
down_revision: Union[str, None] = 'b5d7756411e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='session_status'), nullable=False),
    sa.Column('meeting_type', sa.Enum('GOOGLE_MEET', 'ZOOM', 'WHATSAPP', 'PHONE', 'IN_PERSON', name='session_meeting_type'), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('trainer_notes', sa.Text(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'CLIENT_NO_SHOW', 'TRAINER_NO_SHOW', 'BOTH_PRESENT', name='session_attendance_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on
    # 'uq_password_reset_tokens_token_hash' (password_reset_tokens table).
    # That is out of scope for Task-17.1 (sessions table only) and has been
    # intentionally left out of this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    sa.Enum(name='session_attendance_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_meeting_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
